version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: lab5-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 2001Anton
      MYSQL_DATABASE: blog_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: lab5-blog-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/blog_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 2001Anton
      SERVER_PORT: 8081
    ports:
      - "8081:8081"

volumes:
  db_data:
